### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by charlesoblack** [AlphaZeroIncubator/AlphaZero#11]
Personally, I'd like to have some tests to make sure that our code works as expected, as well as some CI tool to run those tests automatically.

I don't really have a preference for which test arch to use, but I know of `pytest` and `tox`. For CI, I think Travis does UNIX-based CI stuff for free on open source projects, and Appveyor can do Windows based CI (though I don't know if that one is free).

Ideally the tests would all be placed under a `tests/` folder in the root of the repo.

Status: 
- [ ] Black formatting
	- [x] Check Black formatting on pull requests
	- [x] Black auto formatting on commit/merge to master
	- [ ] Clean up separation between pull request/push hooks in Black action
- [x] Unit tests
- [x] flake8

**Comment by PhilipEkfeldt** [comment]
Sounds good! As I mentioned in chat, I have basically no experience with tests but open to learning. 

Other than tests, we can add code formatting and (very much in the future) deployment if we want to host gameplay or similar

**Comment by charlesoblack** [comment]
I added a pre-commit hook with #19 . All you have to do is install `pre-commit`, then in the root folder run `pre-commit install` and it will automatically check if black accepts your commit or not.

A lot less annoying than forgetting to run black and committing, then having to create another commit.

**Comment by PhilipEkfeldt** [comment]
Nice, I usually do on save. I think the CI is just if we just want to force merge anyway and let the action fix the formatting if it's missing.

**Comment by charlesoblack** [comment]
@PhilipEkfeldt do you particularly want the PR part of black automation? I originally just intended for it to run the check and let us know whether it passed or not, so I don't care either way. It would be nice if it made an additional commit on the same branch, instead of in a new PR, though - if you're gonna keep it.

Otherwise I think we're good for now on CI stuff. :) Thanks again for starting this up!

**Comment by charlesoblack** [comment]
Added flake8 since apparently black is not a linter, just a formatter.

**Comment by charlesoblack** [comment]
Flake8 added in #27 .
