### ISSUE TITLE
Tic Tac Toe in an OOP format

### ISSUE THREAD

**Issue by charlesoblack** [AlphaZeroIncubator/AlphaZero#2]
For future-proofing our code, and to start out with tic-tac-toe, we should have a game class that implements things like getting all possible moves, as well as win conditions, for instance.

The reason why we should do this as a class is so that we can easily pass in other games to our NN architecture. Maybe tic-tac-toe should be a subclass of a more general `Game` class that leaves implementation of specific methods for the subclasses? That way all our games can subclass `Game` and we can ensure that the games are all implemented fully.

**Comment by PhilipEkfeldt** [comment]
I agree with subclassing from a generic `Game` class. Some functions I was thinking could be useful for this class:

`GetInitialBoard() -> array/tensor (board)` 
`IsLegalMove(move (binary array/int?), current_player (int?), current_board (array/tensor)) -> Bool`
`MakeMove(move, board) -> board`
`IsFinal(board) -> Bool`

**Comment by charlesoblack** [comment]
Working on this in #8 . The game itself is there, but I'm writing tests for it too.

**Comment by charlesoblack** [comment]
Closed through #8 .
