### ISSUE TITLE
Add Connect4

### ISSUE THREAD

**Issue by charlesoblack** [AlphaZeroIncubator/AlphaZero#21]
Next game to write an API for is Connect 4.

Plans for next games: Abalone (tricky; not a simple 2d grid, it's hexagonal shaped), chess (also tricky: too many moves?), go

**Comment by charlesoblack** [comment]
@homerours did you have any other ideas for games to implement? I feel like you mentioned something but I forgot what it was...

**Comment by homerours** [comment]
Abalone would be really fun! If we manage to train a model for connect4 in a reasonable time, this may be possible.
The game 'reversi' could also be fun.
