### ISSUE TITLE
Training/testing functions

### ISSUE THREAD

**Issue by charlesoblack** [AlphaZeroIncubator/AlphaZero#3]
We should have easy to use training/testing functions for our model where we pass in e.g. the model, the optimizer, number of epochs, etc.

**Comment by PhilipEkfeldt** [comment]
Like I mentioned in the call, I would suggest using [PytorchLightning](https://github.com/PyTorchLightning/pytorch-lightning) for this as it makes managing experiments and logging much easier. Haven't used it with RL though, I imagine the data generation adds complexity to the process.
